collection_acronym_to_collection_name = {
    'arg': 'Argentina',
    'chl': 'Chile',
    'col': 'Colômbia',
    'cub': 'Cuba',
    'esp': 'Espanha',
    'mex': 'México',
    'prt': 'Portugal',
    'boo': 'SciELO Livros',
    'scl': 'Brasil',
    'ssp': 'Saúde Pública',
    'sss': 'Social Sciences',
    'sza': 'África do Sul',
    'ven': 'Venezuela',
    'bio': 'Biodiversity Heritage Library',
    'bol': 'Bolívia',
    'cri': 'Costa Rica',
    'per': 'Peru',
    'pro': 'Proceedings',
    'pry': 'Paraguai',
    'ury': 'Uruguai',
    'wid': 'Índias Ocidentais',
    'cci': 'ComCiência',
    'cic': 'Ciência e Cultura',
    'inv': 'Conhecimento & Inovação',
    'pef': 'Pesquisa FAPESP',
    'edc': 'Educa',
    'ppg': 'Portal de Periódicos Eletrônicos em Geociências',
    'psi': 'Periódicos Eletrônicos em Psicologia',
    'rve': 'Revista de Enfermagem',
    'rvo': 'RevOdonto',
    'ses': 'Portal de Revistas - SES',
    'ecu': 'Equador',
    'rvt': 'RevTur',
    'pre': 'SciELO Preprints',
    'dat': 'SciELO Data',
    'nbr': 'SciELO New Site'
}